services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: DockerFile
        image: kanban-server
        volumes:
            - ./src:/api/src
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
